booksearch/booksearch/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('',include('search.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booksearch/search/urls.py
from django.urls import path
from . import views

app_name='search'
urlpatterns = [
    
    path('', views.IndexView.as_view(), name='index'),
    
    path('book_detail/<int:pk>', views.BookDetailView.as_view(), name='book_detail'),
    
    path('search_result',views.SearchResultView.as_view(),name='search_result'),
]

booksearch/search/models.py
from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=30)    
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)    
    website = models.URLField()

    class Meta:
        ordering = ["-name"]

    def __str__(self):
        return self.name

class Author(models.Model):    
    name = models.CharField(max_length=20)
    biography = models.TextField(max_length=200,blank=True)

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ManyToManyField('Publisher')
    publication_date = models.DateField()
    headshot = models.ImageField(upload_to='book_headshots')
    summary = models.TextField(max_length=300,null=True)
    
    def __str__(self):
        return self.title

booksearch/search/forms.py
from django import forms
from .models import Publisher,Author,Book

class BookForm(forms.ModelForm):
   
    class Meta:
        model = Book
        
        fields = ['title']
       
        

booksearch/search/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .models import Author,Book
import re

        
class IndexView(ListView):
    template_name = "search/index.html" 
    model = Author
   
class BookDetailView(DetailView):
    template_name = "search/book_detail.html"
    context_object_name = 'book_detail'
    model = Book
   
class SearchResultView(ListView):
    template_name = "search/book_list.html"
    model = Book
    
    def get_queryset(self):
        queryset = []
        
        if self.request.GET.get('title'):
            pattern = re.compile(r"^(?=.*" + re.escape(self.request.GET.getlist('title')[0]) +r").*$")
            [queryset.append(i) for i in Book.objects.all() if pattern.match(i.title)]          
            
        elif self.request.GET.get('author'):
            pattern = re.compile(r"^(?=.*" + re.escape(self.request.GET.getlist('author')[0]) +r").*$")
            [queryset.append(i) for i in Book.objects.all() if pattern.match(i.authors.all().first().name)]      
            
            
        elif self.request.GET.get('publisher'):
            pattern = re.compile(r"^(?=.*" + re.escape(self.request.GET.getlist('publisher')[0]) +r").*$")
            [queryset.append(i) for i in Book.objects.all() if pattern.match(i.publisher.all().first().name)]          
           
        else:
            queryset = []
        
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book_list = {"book_list":self.get_queryset()}
        book_summary = []
        [book_summary.append(i.summary) for i in self.get_queryset()]       
        context['json_date'] = {'book_summary':book_summary}
        context.update(book_list)
        
        return context        
        
        
        
        
        
        
        
        
        
        
        
        
        

booksearch/search/templates/search/book_detail.html
<!DOCTYPE html><head>    <meta charset="utf-8" />    <meta name="descriptipn" content="検索">    <title></title>    <style>        .container {            display: flex;            justify-content: center;                    }        .book_image {            width: 250px;            height: 300px;            margin: 10px;            border: 1px dotted #ccc;            text-align: center;            }        .book_detail {            width: 250px;            height: 50px;            margin: 15px 10px;                        }        .book_detail p{            margin: 0px;            }        .book_image img {            width: 200px;            }    </style>    <script>    </script></head><body>    <div class="container">              <div class="book_image">                <img src="{{ book_detail.headshot.url }}">                            </div>            <div class="book_detail">                <p>タイトル：{{ book_detail.title }}</p>                <p><br>概要</br>{{book_detail.summary}}</p>            </div>          </div>     <a href="{% url 'search:index' %}"><p>戻る</p></a>                            

booksearch/search/templates/search/index.html
<p>本の名前から検索する</p><form action="{% url 'search:search_result' %}" method="get">    <input name="title" type="text">    <button type="submit" onclick="location.href='{% url 'search:search_result' %}'">検索する</button></form><p>著者名から検索する</p><form action="{% url 'search:search_result' %}" method="get">    <input name="author" type="text">    <button type="submit" onclick="location.href='{% url 'search:search_result' %}'">検索する</button></form><p>出版社から検索する</p><form action="{% url 'search:search_result' %}" method="get">    <input name="publisher" type="text">    <button type="submit" onclick="location.href='{% url 'search:search_result' %}'">検索する</button></form>